# Configuración del servidor
server:
  port: 8080

# Configuración de la aplicación
spring:
  application:
    name: user-management-application
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Configuración de la base de datos H2
  datasource:
    url: jdbc:h2:file:./database/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS PUBLIC
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# Configuración de logging
logging:
  level:
    root: error
    web: error
    org:
      springframework: info
    es:
      ibm: debug
